### PR TITLE
Toolbox, CI and fixing Require Imports

### PR DESCRIPTION
**Pull request by CohenCyril**
Adding local nix CI + fixing some issues.
After that, a release will be required for monae to be added to mathcomp CI.

### CODE REVIEW

**Comment by CohenCyril** [comment]
After that, a release will be required for monae to be added to mathcomp CI

**Comment by CohenCyril** [comment]
@affeldt-aist would it be possible to merge and release so as to integrate monae in mathcomp CI ASAP?

**Comment by affeldt-aist** [comment]
> @affeldt-aist would it be possible to merge and release so as to integrate monae in mathcomp and HB CI ASAP?

I'll try to but I am sick in bed, let me ping co-workers @t6s @garrigue

**Comment by affeldt-aist** [comment]
I merged and we have also updated the code to be compatible with the new version of infotheo

**Pull request merged**
